# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab2(self):
    self.driver.get("https://demo.opencart.com/")
    self.driver.set_window_size(1053, 665)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".col:nth-child(1) > .product-thumb button:nth-child(1)")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1) > .product-thumb .fa-shopping-cart").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1) > .product-thumb .fa-shopping-cart")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1) > .product-thumb button:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
